/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Text;
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const Category = IDL.Variant({
  'wearables' : IDL.Null,
  'audio' : IDL.Null,
  'accessories' : IDL.Null,
  'hometech' : IDL.Null,
  'computing' : IDL.Null,
  'mobile' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'featured' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageEmoji' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
});
export const Stats = IDL.Record({
  'totalProducts' : IDL.Nat,
  'yearsInnovation' : IDL.Nat,
  'satisfaction' : IDL.Nat,
  'customers' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addToCart' : IDL.Func([IDL.Text], [], []),
  'clearCart' : IDL.Func([], [], []),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductById' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'removeFromCart' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Text;
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const Category = IDL.Variant({
    'wearables' : IDL.Null,
    'audio' : IDL.Null,
    'accessories' : IDL.Null,
    'hometech' : IDL.Null,
    'computing' : IDL.Null,
    'mobile' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'featured' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageEmoji' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
  });
  const Stats = IDL.Record({
    'totalProducts' : IDL.Nat,
    'yearsInnovation' : IDL.Nat,
    'satisfaction' : IDL.Nat,
    'customers' : IDL.Nat,
  });
  
  return IDL.Service({
    'addToCart' : IDL.Func([IDL.Text], [], []),
    'clearCart' : IDL.Func([], [], []),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductById' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'removeFromCart' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };