/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : ProductId, 'quantity' : bigint }
export type Category = { 'wearables' : null } |
  { 'audio' : null } |
  { 'accessories' : null } |
  { 'hometech' : null } |
  { 'computing' : null } |
  { 'mobile' : null };
export interface Product {
  'id' : ProductId,
  'featured' : boolean,
  'name' : string,
  'description' : string,
  'imageEmoji' : string,
  'category' : Category,
  'price' : bigint,
}
export type ProductId = string;
export interface Stats {
  'totalProducts' : bigint,
  'yearsInnovation' : bigint,
  'satisfaction' : bigint,
  'customers' : bigint,
}
export interface _SERVICE {
  'addToCart' : ActorMethod<[string], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getProductById' : ActorMethod<[string], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getStats' : ActorMethod<[], Stats>,
  'removeFromCart' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];